# Nome da pipeline
name: 'Python 3.12 Pipeline'

# Disparadores
trigger:
  branches:
    include:
      - '*'

# Pool de agentes
pool:
  vmImage: 'ubuntu-latest'

# Variáveis
variables:
  python_version: '3.12'

# Estágios do Pipeline
stages:
  - stage: Install
    displayName: 'Install Dependencies'
    jobs:
      - job: Install
        displayName: 'Install'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(python_version)'
              addToPath: true
            displayName: 'Use Python $(python_version)'

          - script: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
            displayName: 'Install Dependencies'

  - stage: Test
    displayName: 'Run Tests'
    dependsOn: Install
    jobs:
      - job: Test
        displayName: 'Test'
        steps:
          - script: |
              pytest
            displayName: 'Run Tests'

  - stage: Build
    displayName: 'Build Project'
    dependsOn: Test
    jobs:
      - job: Build
        displayName: 'Build'
        steps:
          - script: |
              python setup.py sdist bdist_wheel
            displayName: 'Build Project'
